overwrite: true
schema:
    - './schema.graphql'
documents:
    - './src/graphql/**/*.gql'
config:
    scalars:
        DateTime: 'string'
        JSON: '{ [key: string]: any }'
        Upload: 'unknown'
hooks:
    afterAllFileWrite:
        - ../../node_modules/.bin/prettier --write
generates:
    src/graphql/introspection.generated.json:
        plugins:
            - introspection
        config:
            minify: true
            descriptions: false
    src/graphql/types.generated.ts:
        plugins:
            - typescript
            - fragment-matcher
            - typescript-operations
            - typescript-react-apollo
        config:
            withHooks: true
            avoidOptionals:
                field: true
                object: true
