on:
    pull_request:
        branches:
            - master
            - develop
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn lint
    build_api:
        name: Build API
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: cd ./packages/api && yarn orm:generate && yarn build
    build_web:
        name: Build Web
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: cd ./packages/web && yarn codegen && yarn build
